// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paisespb/paises.proto

package paisespb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Descricao da mensagem pais
type Pais struct {
	Codigo               int32                `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Nome                 string               `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	InicioVigencia       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=inicioVigencia,proto3" json:"inicioVigencia,omitempty"`
	FimVigencia          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=fimVigencia,proto3" json:"fimVigencia,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Pais) Reset()         { *m = Pais{} }
func (m *Pais) String() string { return proto.CompactTextString(m) }
func (*Pais) ProtoMessage()    {}
func (*Pais) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{0}
}

func (m *Pais) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pais.Unmarshal(m, b)
}
func (m *Pais) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pais.Marshal(b, m, deterministic)
}
func (m *Pais) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pais.Merge(m, src)
}
func (m *Pais) XXX_Size() int {
	return xxx_messageInfo_Pais.Size(m)
}
func (m *Pais) XXX_DiscardUnknown() {
	xxx_messageInfo_Pais.DiscardUnknown(m)
}

var xxx_messageInfo_Pais proto.InternalMessageInfo

func (m *Pais) GetCodigo() int32 {
	if m != nil {
		return m.Codigo
	}
	return 0
}

func (m *Pais) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *Pais) GetInicioVigencia() *timestamp.Timestamp {
	if m != nil {
		return m.InicioVigencia
	}
	return nil
}

func (m *Pais) GetFimVigencia() *timestamp.Timestamp {
	if m != nil {
		return m.FimVigencia
	}
	return nil
}

type Mensagem struct {
	Codigo               int32    `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Mensagem             string   `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mensagem) Reset()         { *m = Mensagem{} }
func (m *Mensagem) String() string { return proto.CompactTextString(m) }
func (*Mensagem) ProtoMessage()    {}
func (*Mensagem) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{1}
}

func (m *Mensagem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mensagem.Unmarshal(m, b)
}
func (m *Mensagem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mensagem.Marshal(b, m, deterministic)
}
func (m *Mensagem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mensagem.Merge(m, src)
}
func (m *Mensagem) XXX_Size() int {
	return xxx_messageInfo_Mensagem.Size(m)
}
func (m *Mensagem) XXX_DiscardUnknown() {
	xxx_messageInfo_Mensagem.DiscardUnknown(m)
}

var xxx_messageInfo_Mensagem proto.InternalMessageInfo

func (m *Mensagem) GetCodigo() int32 {
	if m != nil {
		return m.Codigo
	}
	return 0
}

func (m *Mensagem) GetMensagem() string {
	if m != nil {
		return m.Mensagem
	}
	return ""
}

// Criar um pais
type CriarPaisRequest struct {
	Pais                 *Pais    `protobuf:"bytes,1,opt,name=pais,proto3" json:"pais,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriarPaisRequest) Reset()         { *m = CriarPaisRequest{} }
func (m *CriarPaisRequest) String() string { return proto.CompactTextString(m) }
func (*CriarPaisRequest) ProtoMessage()    {}
func (*CriarPaisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{2}
}

func (m *CriarPaisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarPaisRequest.Unmarshal(m, b)
}
func (m *CriarPaisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarPaisRequest.Marshal(b, m, deterministic)
}
func (m *CriarPaisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarPaisRequest.Merge(m, src)
}
func (m *CriarPaisRequest) XXX_Size() int {
	return xxx_messageInfo_CriarPaisRequest.Size(m)
}
func (m *CriarPaisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarPaisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CriarPaisRequest proto.InternalMessageInfo

func (m *CriarPaisRequest) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

//
type CriarPaisResponse struct {
	Pais                 *Pais     `protobuf:"bytes,1,opt,name=pais,proto3" json:"pais,omitempty"`
	Mensagem             *Mensagem `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CriarPaisResponse) Reset()         { *m = CriarPaisResponse{} }
func (m *CriarPaisResponse) String() string { return proto.CompactTextString(m) }
func (*CriarPaisResponse) ProtoMessage()    {}
func (*CriarPaisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{3}
}

func (m *CriarPaisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriarPaisResponse.Unmarshal(m, b)
}
func (m *CriarPaisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriarPaisResponse.Marshal(b, m, deterministic)
}
func (m *CriarPaisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriarPaisResponse.Merge(m, src)
}
func (m *CriarPaisResponse) XXX_Size() int {
	return xxx_messageInfo_CriarPaisResponse.Size(m)
}
func (m *CriarPaisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CriarPaisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CriarPaisResponse proto.InternalMessageInfo

func (m *CriarPaisResponse) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

func (m *CriarPaisResponse) GetMensagem() *Mensagem {
	if m != nil {
		return m.Mensagem
	}
	return nil
}

// Criar um pais
type ModificarPaisRequest struct {
	Pais                 *Pais    `protobuf:"bytes,1,opt,name=pais,proto3" json:"pais,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModificarPaisRequest) Reset()         { *m = ModificarPaisRequest{} }
func (m *ModificarPaisRequest) String() string { return proto.CompactTextString(m) }
func (*ModificarPaisRequest) ProtoMessage()    {}
func (*ModificarPaisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{4}
}

func (m *ModificarPaisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModificarPaisRequest.Unmarshal(m, b)
}
func (m *ModificarPaisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModificarPaisRequest.Marshal(b, m, deterministic)
}
func (m *ModificarPaisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModificarPaisRequest.Merge(m, src)
}
func (m *ModificarPaisRequest) XXX_Size() int {
	return xxx_messageInfo_ModificarPaisRequest.Size(m)
}
func (m *ModificarPaisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModificarPaisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModificarPaisRequest proto.InternalMessageInfo

func (m *ModificarPaisRequest) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

//
type ModificarPaisResponse struct {
	Pais                 *Pais     `protobuf:"bytes,1,opt,name=pais,proto3" json:"pais,omitempty"`
	Mensagem             *Mensagem `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModificarPaisResponse) Reset()         { *m = ModificarPaisResponse{} }
func (m *ModificarPaisResponse) String() string { return proto.CompactTextString(m) }
func (*ModificarPaisResponse) ProtoMessage()    {}
func (*ModificarPaisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{5}
}

func (m *ModificarPaisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModificarPaisResponse.Unmarshal(m, b)
}
func (m *ModificarPaisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModificarPaisResponse.Marshal(b, m, deterministic)
}
func (m *ModificarPaisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModificarPaisResponse.Merge(m, src)
}
func (m *ModificarPaisResponse) XXX_Size() int {
	return xxx_messageInfo_ModificarPaisResponse.Size(m)
}
func (m *ModificarPaisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModificarPaisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModificarPaisResponse proto.InternalMessageInfo

func (m *ModificarPaisResponse) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

func (m *ModificarPaisResponse) GetMensagem() *Mensagem {
	if m != nil {
		return m.Mensagem
	}
	return nil
}

type ExcluirPaisRequest struct {
	Codigo               int32    `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExcluirPaisRequest) Reset()         { *m = ExcluirPaisRequest{} }
func (m *ExcluirPaisRequest) String() string { return proto.CompactTextString(m) }
func (*ExcluirPaisRequest) ProtoMessage()    {}
func (*ExcluirPaisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{6}
}

func (m *ExcluirPaisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExcluirPaisRequest.Unmarshal(m, b)
}
func (m *ExcluirPaisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExcluirPaisRequest.Marshal(b, m, deterministic)
}
func (m *ExcluirPaisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExcluirPaisRequest.Merge(m, src)
}
func (m *ExcluirPaisRequest) XXX_Size() int {
	return xxx_messageInfo_ExcluirPaisRequest.Size(m)
}
func (m *ExcluirPaisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExcluirPaisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExcluirPaisRequest proto.InternalMessageInfo

func (m *ExcluirPaisRequest) GetCodigo() int32 {
	if m != nil {
		return m.Codigo
	}
	return 0
}

type ExcluirPaisResponse struct {
	Mensagem             *Mensagem `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExcluirPaisResponse) Reset()         { *m = ExcluirPaisResponse{} }
func (m *ExcluirPaisResponse) String() string { return proto.CompactTextString(m) }
func (*ExcluirPaisResponse) ProtoMessage()    {}
func (*ExcluirPaisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{7}
}

func (m *ExcluirPaisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExcluirPaisResponse.Unmarshal(m, b)
}
func (m *ExcluirPaisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExcluirPaisResponse.Marshal(b, m, deterministic)
}
func (m *ExcluirPaisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExcluirPaisResponse.Merge(m, src)
}
func (m *ExcluirPaisResponse) XXX_Size() int {
	return xxx_messageInfo_ExcluirPaisResponse.Size(m)
}
func (m *ExcluirPaisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExcluirPaisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExcluirPaisResponse proto.InternalMessageInfo

func (m *ExcluirPaisResponse) GetMensagem() *Mensagem {
	if m != nil {
		return m.Mensagem
	}
	return nil
}

type BuscarPaisRequest struct {
	Codigo               int32    `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuscarPaisRequest) Reset()         { *m = BuscarPaisRequest{} }
func (m *BuscarPaisRequest) String() string { return proto.CompactTextString(m) }
func (*BuscarPaisRequest) ProtoMessage()    {}
func (*BuscarPaisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{8}
}

func (m *BuscarPaisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuscarPaisRequest.Unmarshal(m, b)
}
func (m *BuscarPaisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuscarPaisRequest.Marshal(b, m, deterministic)
}
func (m *BuscarPaisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuscarPaisRequest.Merge(m, src)
}
func (m *BuscarPaisRequest) XXX_Size() int {
	return xxx_messageInfo_BuscarPaisRequest.Size(m)
}
func (m *BuscarPaisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuscarPaisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuscarPaisRequest proto.InternalMessageInfo

func (m *BuscarPaisRequest) GetCodigo() int32 {
	if m != nil {
		return m.Codigo
	}
	return 0
}

type BuscarPaisResponse struct {
	Pais                 *Pais     `protobuf:"bytes,1,opt,name=pais,proto3" json:"pais,omitempty"`
	Mensagem             *Mensagem `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuscarPaisResponse) Reset()         { *m = BuscarPaisResponse{} }
func (m *BuscarPaisResponse) String() string { return proto.CompactTextString(m) }
func (*BuscarPaisResponse) ProtoMessage()    {}
func (*BuscarPaisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{9}
}

func (m *BuscarPaisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuscarPaisResponse.Unmarshal(m, b)
}
func (m *BuscarPaisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuscarPaisResponse.Marshal(b, m, deterministic)
}
func (m *BuscarPaisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuscarPaisResponse.Merge(m, src)
}
func (m *BuscarPaisResponse) XXX_Size() int {
	return xxx_messageInfo_BuscarPaisResponse.Size(m)
}
func (m *BuscarPaisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuscarPaisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuscarPaisResponse proto.InternalMessageInfo

func (m *BuscarPaisResponse) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

func (m *BuscarPaisResponse) GetMensagem() *Mensagem {
	if m != nil {
		return m.Mensagem
	}
	return nil
}

type BuscarTodosPaisesRequest struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuscarTodosPaisesRequest) Reset()         { *m = BuscarTodosPaisesRequest{} }
func (m *BuscarTodosPaisesRequest) String() string { return proto.CompactTextString(m) }
func (*BuscarTodosPaisesRequest) ProtoMessage()    {}
func (*BuscarTodosPaisesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{10}
}

func (m *BuscarTodosPaisesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuscarTodosPaisesRequest.Unmarshal(m, b)
}
func (m *BuscarTodosPaisesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuscarTodosPaisesRequest.Marshal(b, m, deterministic)
}
func (m *BuscarTodosPaisesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuscarTodosPaisesRequest.Merge(m, src)
}
func (m *BuscarTodosPaisesRequest) XXX_Size() int {
	return xxx_messageInfo_BuscarTodosPaisesRequest.Size(m)
}
func (m *BuscarTodosPaisesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuscarTodosPaisesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuscarTodosPaisesRequest proto.InternalMessageInfo

func (m *BuscarTodosPaisesRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *BuscarTodosPaisesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type BuscarTodosPaisesResponse struct {
	Mensagem             *Mensagem `protobuf:"bytes,1,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Pais                 *Pais     `protobuf:"bytes,2,opt,name=pais,proto3" json:"pais,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuscarTodosPaisesResponse) Reset()         { *m = BuscarTodosPaisesResponse{} }
func (m *BuscarTodosPaisesResponse) String() string { return proto.CompactTextString(m) }
func (*BuscarTodosPaisesResponse) ProtoMessage()    {}
func (*BuscarTodosPaisesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c0680d16164d15, []int{11}
}

func (m *BuscarTodosPaisesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuscarTodosPaisesResponse.Unmarshal(m, b)
}
func (m *BuscarTodosPaisesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuscarTodosPaisesResponse.Marshal(b, m, deterministic)
}
func (m *BuscarTodosPaisesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuscarTodosPaisesResponse.Merge(m, src)
}
func (m *BuscarTodosPaisesResponse) XXX_Size() int {
	return xxx_messageInfo_BuscarTodosPaisesResponse.Size(m)
}
func (m *BuscarTodosPaisesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuscarTodosPaisesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuscarTodosPaisesResponse proto.InternalMessageInfo

func (m *BuscarTodosPaisesResponse) GetMensagem() *Mensagem {
	if m != nil {
		return m.Mensagem
	}
	return nil
}

func (m *BuscarTodosPaisesResponse) GetPais() *Pais {
	if m != nil {
		return m.Pais
	}
	return nil
}

func init() {
	proto.RegisterType((*Pais)(nil), "paises.Pais")
	proto.RegisterType((*Mensagem)(nil), "paises.Mensagem")
	proto.RegisterType((*CriarPaisRequest)(nil), "paises.CriarPaisRequest")
	proto.RegisterType((*CriarPaisResponse)(nil), "paises.CriarPaisResponse")
	proto.RegisterType((*ModificarPaisRequest)(nil), "paises.ModificarPaisRequest")
	proto.RegisterType((*ModificarPaisResponse)(nil), "paises.ModificarPaisResponse")
	proto.RegisterType((*ExcluirPaisRequest)(nil), "paises.ExcluirPaisRequest")
	proto.RegisterType((*ExcluirPaisResponse)(nil), "paises.ExcluirPaisResponse")
	proto.RegisterType((*BuscarPaisRequest)(nil), "paises.BuscarPaisRequest")
	proto.RegisterType((*BuscarPaisResponse)(nil), "paises.BuscarPaisResponse")
	proto.RegisterType((*BuscarTodosPaisesRequest)(nil), "paises.BuscarTodosPaisesRequest")
	proto.RegisterType((*BuscarTodosPaisesResponse)(nil), "paises.BuscarTodosPaisesResponse")
}

func init() { proto.RegisterFile("paisespb/paises.proto", fileDescriptor_02c0680d16164d15) }

var fileDescriptor_02c0680d16164d15 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdb, 0x34, 0x4a, 0xc7, 0x80, 0x9a, 0x81, 0x22, 0x77, 0xf9, 0x32, 0x3e, 0x45, 0xa2,
	0x72, 0x50, 0xe0, 0xc0, 0x01, 0x21, 0x94, 0x08, 0x4e, 0x2d, 0xaa, 0xdc, 0xaa, 0x87, 0xde, 0x1c,
	0x67, 0x63, 0x8d, 0xa8, 0xbd, 0xc6, 0x6b, 0x23, 0xc4, 0x0f, 0xe0, 0x17, 0xf1, 0x03, 0x91, 0xed,
	0xb5, 0xb1, 0x1d, 0x9b, 0x88, 0x4a, 0xb9, 0x79, 0x3c, 0x6f, 0xde, 0xbc, 0x99, 0x7d, 0xbb, 0x70,
	0x1c, 0xb9, 0x24, 0xb9, 0x8c, 0x96, 0xd3, 0xe2, 0xc3, 0x8e, 0x62, 0x91, 0x08, 0x1c, 0x16, 0x11,
	0x7b, 0xe1, 0x0b, 0xe1, 0xdf, 0xf2, 0x69, 0xfe, 0x77, 0x99, 0xae, 0xa7, 0x09, 0x05, 0x5c, 0x26,
	0x6e, 0x10, 0x15, 0x40, 0xeb, 0xb7, 0x06, 0x83, 0x0b, 0x97, 0x24, 0x3e, 0x86, 0xa1, 0x27, 0x56,
	0xe4, 0x0b, 0x43, 0x33, 0xb5, 0xc9, 0x81, 0xa3, 0x22, 0x44, 0x18, 0x84, 0x22, 0xe0, 0xc6, 0x9e,
	0xa9, 0x4d, 0x0e, 0x9d, 0xfc, 0x1b, 0xe7, 0xf0, 0x80, 0x42, 0xf2, 0x48, 0x5c, 0x93, 0xcf, 0x43,
	0x8f, 0x5c, 0x63, 0xdf, 0xd4, 0x26, 0xfa, 0x8c, 0xd9, 0x45, 0x3b, 0xbb, 0x6c, 0x67, 0x5f, 0x95,
	0xed, 0x9c, 0x56, 0x05, 0xbe, 0x07, 0x7d, 0x4d, 0x41, 0x45, 0x30, 0xd8, 0x4a, 0x50, 0x87, 0x5b,
	0x1f, 0x60, 0x74, 0xce, 0x43, 0xe9, 0xfa, 0x3c, 0xe8, 0x55, 0xce, 0x60, 0x14, 0x28, 0x8c, 0x52,
	0x5f, 0xc5, 0xd6, 0x5b, 0x38, 0x5a, 0xc4, 0xe4, 0xc6, 0xd9, 0xe8, 0x0e, 0xff, 0x96, 0x72, 0x99,
	0xa0, 0x09, 0x83, 0x6c, 0x6b, 0x39, 0x8b, 0x3e, 0xbb, 0x67, 0xab, 0x85, 0xe6, 0x90, 0x3c, 0x63,
	0x79, 0x30, 0xae, 0x55, 0xc9, 0x48, 0x84, 0x92, 0x6f, 0x2f, 0xc3, 0xd3, 0x96, 0x10, 0x7d, 0x76,
	0x54, 0xa2, 0xca, 0x21, 0x6a, 0xd2, 0xde, 0xc1, 0xa3, 0x73, 0xb1, 0xa2, 0x35, 0x79, 0xff, 0x2b,
	0xcf, 0x87, 0xe3, 0x56, 0xe5, 0x8e, 0x24, 0x9e, 0x02, 0x7e, 0xfa, 0xe1, 0xdd, 0xa6, 0xd4, 0x10,
	0xd8, 0x73, 0x0e, 0xd6, 0x02, 0x1e, 0x36, 0xd0, 0x4a, 0x54, 0xbd, 0xa5, 0xb6, 0xb5, 0xe5, 0x2b,
	0x18, 0xcf, 0x53, 0xd9, 0x5a, 0x49, 0x5f, 0xc7, 0x15, 0x60, 0x1d, 0xbc, 0xa3, 0x2d, 0x5c, 0x83,
	0x51, 0x74, 0xb9, 0x12, 0x2b, 0x21, 0x2f, 0x72, 0x5c, 0xa9, 0xec, 0x39, 0x40, 0xe4, 0xfa, 0xfc,
	0x4b, 0x1a, 0x2c, 0x79, 0xac, 0xd4, 0xd5, 0xfe, 0x64, 0xde, 0xcc, 0xa2, 0x4b, 0xfa, 0x59, 0xdc,
	0xac, 0x03, 0xa7, 0x8a, 0xad, 0xaf, 0x70, 0xd2, 0xc1, 0x7b, 0x97, 0xad, 0x55, 0x23, 0xef, 0xf5,
	0x8d, 0x3c, 0xfb, 0xb5, 0x0f, 0x7a, 0x16, 0x5e, 0xf2, 0xf8, 0x3b, 0x79, 0x1c, 0x3f, 0xc2, 0x61,
	0x65, 0x71, 0x34, 0xca, 0x82, 0xf6, 0x5d, 0x61, 0x27, 0x1d, 0x19, 0xa5, 0xf0, 0x0c, 0xee, 0x37,
	0x5c, 0x88, 0x4f, 0x2b, 0x81, 0x1d, 0xb6, 0x66, 0xcf, 0x7a, 0xb2, 0x8a, 0xed, 0x33, 0xe8, 0x35,
	0xf3, 0x20, 0x2b, 0xd1, 0x9b, 0xfe, 0x63, 0x4f, 0x3a, 0x73, 0x8a, 0x67, 0x01, 0xf0, 0xd7, 0x12,
	0x58, 0xc9, 0xdf, 0xf0, 0x14, 0x63, 0x5d, 0x29, 0x45, 0x72, 0x03, 0xe3, 0x33, 0x92, 0x49, 0xe3,
	0x64, 0xd0, 0x6c, 0x16, 0x6c, 0x9a, 0x81, 0xbd, 0xfc, 0x07, 0xa2, 0x60, 0x7e, 0xad, 0xcd, 0xe1,
	0x66, 0x54, 0x3e, 0xe5, 0xcb, 0x61, 0xfe, 0xfc, 0xbd, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x59,
	0xd5, 0x9e, 0x68, 0xdd, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaisServiceClient is the client API for PaisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaisServiceClient interface {
	CriarPais(ctx context.Context, in *CriarPaisRequest, opts ...grpc.CallOption) (*CriarPaisResponse, error)
	ModificarPais(ctx context.Context, in *ModificarPaisRequest, opts ...grpc.CallOption) (*ModificarPaisResponse, error)
	ExcluirPais(ctx context.Context, in *ExcluirPaisRequest, opts ...grpc.CallOption) (*ExcluirPaisResponse, error)
	BuscarPais(ctx context.Context, in *BuscarPaisRequest, opts ...grpc.CallOption) (*BuscarPaisResponse, error)
	ListarTodosPaises(ctx context.Context, in *BuscarTodosPaisesRequest, opts ...grpc.CallOption) (PaisService_ListarTodosPaisesClient, error)
}

type paisServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaisServiceClient(cc *grpc.ClientConn) PaisServiceClient {
	return &paisServiceClient{cc}
}

func (c *paisServiceClient) CriarPais(ctx context.Context, in *CriarPaisRequest, opts ...grpc.CallOption) (*CriarPaisResponse, error) {
	out := new(CriarPaisResponse)
	err := c.cc.Invoke(ctx, "/paises.PaisService/CriarPais", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paisServiceClient) ModificarPais(ctx context.Context, in *ModificarPaisRequest, opts ...grpc.CallOption) (*ModificarPaisResponse, error) {
	out := new(ModificarPaisResponse)
	err := c.cc.Invoke(ctx, "/paises.PaisService/ModificarPais", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paisServiceClient) ExcluirPais(ctx context.Context, in *ExcluirPaisRequest, opts ...grpc.CallOption) (*ExcluirPaisResponse, error) {
	out := new(ExcluirPaisResponse)
	err := c.cc.Invoke(ctx, "/paises.PaisService/ExcluirPais", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paisServiceClient) BuscarPais(ctx context.Context, in *BuscarPaisRequest, opts ...grpc.CallOption) (*BuscarPaisResponse, error) {
	out := new(BuscarPaisResponse)
	err := c.cc.Invoke(ctx, "/paises.PaisService/BuscarPais", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paisServiceClient) ListarTodosPaises(ctx context.Context, in *BuscarTodosPaisesRequest, opts ...grpc.CallOption) (PaisService_ListarTodosPaisesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PaisService_serviceDesc.Streams[0], "/paises.PaisService/ListarTodosPaises", opts...)
	if err != nil {
		return nil, err
	}
	x := &paisServiceListarTodosPaisesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PaisService_ListarTodosPaisesClient interface {
	Recv() (*BuscarTodosPaisesResponse, error)
	grpc.ClientStream
}

type paisServiceListarTodosPaisesClient struct {
	grpc.ClientStream
}

func (x *paisServiceListarTodosPaisesClient) Recv() (*BuscarTodosPaisesResponse, error) {
	m := new(BuscarTodosPaisesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PaisServiceServer is the server API for PaisService service.
type PaisServiceServer interface {
	CriarPais(context.Context, *CriarPaisRequest) (*CriarPaisResponse, error)
	ModificarPais(context.Context, *ModificarPaisRequest) (*ModificarPaisResponse, error)
	ExcluirPais(context.Context, *ExcluirPaisRequest) (*ExcluirPaisResponse, error)
	BuscarPais(context.Context, *BuscarPaisRequest) (*BuscarPaisResponse, error)
	ListarTodosPaises(*BuscarTodosPaisesRequest, PaisService_ListarTodosPaisesServer) error
}

// UnimplementedPaisServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaisServiceServer struct {
}

func (*UnimplementedPaisServiceServer) CriarPais(ctx context.Context, req *CriarPaisRequest) (*CriarPaisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CriarPais not implemented")
}
func (*UnimplementedPaisServiceServer) ModificarPais(ctx context.Context, req *ModificarPaisRequest) (*ModificarPaisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModificarPais not implemented")
}
func (*UnimplementedPaisServiceServer) ExcluirPais(ctx context.Context, req *ExcluirPaisRequest) (*ExcluirPaisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExcluirPais not implemented")
}
func (*UnimplementedPaisServiceServer) BuscarPais(ctx context.Context, req *BuscarPaisRequest) (*BuscarPaisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuscarPais not implemented")
}
func (*UnimplementedPaisServiceServer) ListarTodosPaises(req *BuscarTodosPaisesRequest, srv PaisService_ListarTodosPaisesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListarTodosPaises not implemented")
}

func RegisterPaisServiceServer(s *grpc.Server, srv PaisServiceServer) {
	s.RegisterService(&_PaisService_serviceDesc, srv)
}

func _PaisService_CriarPais_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriarPaisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaisServiceServer).CriarPais(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paises.PaisService/CriarPais",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaisServiceServer).CriarPais(ctx, req.(*CriarPaisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaisService_ModificarPais_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModificarPaisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaisServiceServer).ModificarPais(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paises.PaisService/ModificarPais",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaisServiceServer).ModificarPais(ctx, req.(*ModificarPaisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaisService_ExcluirPais_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExcluirPaisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaisServiceServer).ExcluirPais(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paises.PaisService/ExcluirPais",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaisServiceServer).ExcluirPais(ctx, req.(*ExcluirPaisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaisService_BuscarPais_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuscarPaisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaisServiceServer).BuscarPais(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paises.PaisService/BuscarPais",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaisServiceServer).BuscarPais(ctx, req.(*BuscarPaisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaisService_ListarTodosPaises_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuscarTodosPaisesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaisServiceServer).ListarTodosPaises(m, &paisServiceListarTodosPaisesServer{stream})
}

type PaisService_ListarTodosPaisesServer interface {
	Send(*BuscarTodosPaisesResponse) error
	grpc.ServerStream
}

type paisServiceListarTodosPaisesServer struct {
	grpc.ServerStream
}

func (x *paisServiceListarTodosPaisesServer) Send(m *BuscarTodosPaisesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PaisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paises.PaisService",
	HandlerType: (*PaisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CriarPais",
			Handler:    _PaisService_CriarPais_Handler,
		},
		{
			MethodName: "ModificarPais",
			Handler:    _PaisService_ModificarPais_Handler,
		},
		{
			MethodName: "ExcluirPais",
			Handler:    _PaisService_ExcluirPais_Handler,
		},
		{
			MethodName: "BuscarPais",
			Handler:    _PaisService_BuscarPais_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListarTodosPaises",
			Handler:       _PaisService_ListarTodosPaises_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "paisespb/paises.proto",
}
