
pipeline {
    agent any

    environment {
        DOCKER_IMAGE_TAG = "icorrea/api-paises-grpc:${env.BUILD_ID}"
        registryCredential = 'api-paises-grpc'
        dockerImage = ''
    }

    stages {
        stage('Git Clone') {
            steps {
                    git 'https://github.com/italiviocorrea/golang/tree/master/grpc/paises'
                  }
        }
        stage('Build Image') {
            steps {
                echo "Build docker image"
                script {
                    dockerImage = docker.build("${env.DOCKER_IMAGE_TAG}",  '-f ./Dockerfile .')
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing the app"
            }
        }
        stage('Push') {
            steps {
                script {
                   docker.withRegistry( '', registryCredential ) {
                      dockerImage.push()
                   }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the Docker image"
            }
        }
        stage('Verify') {
            parallel {
                stage('Verify home') {
                    agent any
                    steps {
                        echo "HTTP request to verify home"
                    }
                }
                stage('Verify health check') {
                    agent any
                    steps {
                        echo "HTTP request to verify application health check"
                    }
                }
                stage('Verify regression tests') {
                    agent any
                    steps {
                        echo "Running regression test suite"
                    }
                }
            }
        }
    }
}