version: '3.2'


services:

#    dfe_paises:
#        depends_on:
#            - msssql
#        image: encat_paises:1.0
#        expose:
#          - 8080
#        ports:
#            - 8080:8080
#        networks:
#          - dfe_net
#        environment:
#          - API_SRV_ADDR=0.0.0.0:8080
#          - API_DB_HOST=dbpaises
#          - API_DB_USER=sa
#          - API_DB_PWD=senha#123
#          - API_DB_PORT=1433
#          - API_DB_NAME=dbpaises
#          - API_SRV_CONTEXT=/dfe/v1
#          - API_SRV_LOGLEVEL=4

  zookeeper:
    image: icorrea/zookeeper:0.10-centos7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - dfe_net

  kafka:
    image: icorrea/kafka:0.10-centos7
    ports:
     - 9092:9092
    networks:
      - dfe_net
    depends_on:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    expose:
      - 1433
    ports:
      - 1433:1433
    networks:
      - dfe_net
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=Senha123
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - ~/srv/mssql/dbpaises:/var/opt/mssql

  connect:
    image: icorrea/connect:0.10-centos7
    ports:
     - 8083:8083
    networks:
      - dfe_net
    depends_on:
     - kafka
     - sqlserver
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses

  # A web based interface for managing your docker containers.
  portainer:
    image: portainer/portainer
    command: --templates http://templates/templates.json
    networks:
      - dfe_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/srv/cassandra/portainer-data:/data
    # Enable you to access potainers web interface from your host machine
    # using http://localhost:10001
    ports:
      - "10001:9000"


networks:
  dfe_net:
    external: true


